### ISSUE TITLE
Subfamily names with Tribe as verbatim are Tribes [=Ghouls]

### ISSUE THREAD

**Issue by mjy** [chalcid/ucd#37]
There are ~299 records to update at the outset of this issue.

If you see a Family name, and there is no associated synonymy with it, then this is the most likely underlying issue.

In most cases the help in `4.15 – Scenario: How to handle tribes and subtribes.` resolves the issue.   !! The basic problem is renaming a name to the value in verbatim_name field. !!

In addition keeping in mind the following might be useful:

* Check that the parent for each of corresponding family group names is properly nested (see soft validation for potential help here) 
* Use the relationship `family-group name form of` if the name is not considered valid
* Use the status "Valid" if the name is now valid, but there are (past) relationship that are making it currently invalid
* You should not have to use the synonymy or clone tools during the basic fixes needed here

**Comment by LocoDelAssembly** [comment]
Cmd to run on sandbox: `nohup rake rake ucd:resurrect_ghoul_family_group_names > resurrect_ghoul_family_group_names.log 2>&1 &`

**Comment by LocoDelAssembly** [comment]
[resurrect_ghoul_family_group_names.log](https://github.com/chalcid/ucd/files/11083351/resurrect_ghoul_family_group_names.log)

**Comment by LocoDelAssembly** [comment]
[update_species_names_with_verbatim_and_legal_original_spellings.log](https://github.com/chalcid/ucd/files/11091450/update_species_names_with_verbatim_and_legal_original_spellings.log)
