### ISSUE TITLE
Update species group names to their original form when provided and form is valid

### ISSUE THREAD

**Issue by mjy** [chalcid/ucd#41]
Run `rake ucd:update_species_names_with_verbatim_and_legal_original_spellings`.

!! Ensure stdout/log is pasted here to complete.

Code at https://github.com/chalcid/tw_curation/blob/master/tasks/ucd.rake#L423

**Comment by LocoDelAssembly** [comment]
Cmd to run on sandbox: `PROJECT_ID_OVERRIDE=225 nohup rake ucd:update_species_names_with_verbatim_and_legal_original_spellings > update_species_names_with_verbatim_and_legal_original_spellings.log 2>&1 &`

**Comment by LocoDelAssembly** [comment]
[update_species_names_with_verbatim_and_legal_original_spellings.log](https://github.com/chalcid/ucd/files/11083559/update_species_names_with_verbatim_and_legal_original_spellings.log)

**Comment by LocoDelAssembly** [comment]
Cmd to run in production: `nohup rake ucd:update_species_names_with_verbatim_and_legal_original_spellings > update_species_names_with_verbatim_and_legal_original_spellings.log 2>&1 &`

**Comment by LocoDelAssembly** [comment]
[resurrect_ghoul_family_group_names.log](https://github.com/chalcid/ucd/files/11091355/resurrect_ghoul_family_group_names.log)
